### ISSUE TITLE
Feature Request: Differentiate groups from permission sets

### ISSUE THREAD

**Issue by systemsfixer** [ravinarayanan89/EasyCrudAndFls#1]
Problem:

When editing Permission sets in your utility, if a Group has FLS removed from it, errors are thrown. 

Proposed solution:
Similar to how Profiles have a pill icon stating they are profiles, ideally Groups would be similarly differentiated. I think this can be referenced in via the Type field on the PermissionSet object where Type = `Group`.

Also ability to filter on type would be great.

**Comment by ravinarayanan89** [comment]
Thanks for your time with testing the app and providing the suggestion. I have added the support for PermissionSetGroups.
